### ISSUE TITLE
Node.js v6 support

### ISSUE THREAD

**Issue by missingdays** [timhuff/canvas-phash#2]
Canvas-phash doesn't work with node v6 at the moment because of the breaking changes in Buffer. 
Error message

```
Unhandled rejection Error: If encoding is specified then the first argument must be a string
    at new Buffer (buffer.js:69:13)
    at /srv/missingdays/Projects/ed3/visual-testing/node_modules/canvas-phash/index.js:127:18
```

Can you please adapt your library to new version of node.js, without breaking node 4 support?

**Comment by timhuff** [comment]
Thanks for the PR. I'll publish this to npm.

**Comment by timhuff** [comment]
Alright. This should be ready to install via npm. Version 2.1.0
